spring:
  application:
    name: arquiteturaz
  datasource:
    url: jdbc:h2:mem:tb_todo
    username: sa
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-todos
server:
  port: 8081