POST localhost:8080/produtos
Content-Type: application/json

{
  "nome": "Tv",
  "descricao": "43 polegadas Samsung",
  "preco": 1670.00
}
###

GET localhost:8080/produtos/gh
Content-Type: application/json
###