@id = 59c253fd-61bc-43b2-8cda-3d438a3523db
@nome = Tv
###

POST localhost:8080/produtos
Content-Type: application/json

{
  "nome": "Tv",
  "descricao": "43 polegadas Samsung",
  "preco": 1670.00
}
###

GET localhost:8080/produtos/{{id}}
Content-Type: application/json
###

DELETE localhost:8080/produtos/{{id}}
Content-Type: application/json
###

PUT localhost:8080/produtos/{{id}}
Content-Type: application/json

{
  "nome": "Tv",
  "descricao": "43 polegadas Samsung",
  "preco": 1650.00
}
###

GET localhost:8080/produtos?nome={{nome}}
Content-Type: application/json
###